# Image configuration
image:
  registry: "registry.example.com/traditional-saju"
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: "regcred"

# Application configuration
app:
  imageName: "traditional-saju"
  enabled: true
  env: "prod"
  replicaCount: 2
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

# Database configuration
database:
  existingSecret: ""
  host: "postgres"
  port: 5432
  dbName: "traditional_saju"
  sslMode: "require"
  auth:
    username: "postgres"
    password: "postgres"
  migration:
    username: "postgres"
    password: "postgres"

# Redis configuration
redis:
  existingSecret: ""
  host: "redis"
  port: 6379
  password: ""

# JWT configuration
jwt:
  existingSecret: ""
  accessTokenSecret: ""
  refreshTokenSecret: ""
  accessTokenExpiresIn: 900
  refreshTokenExpiresIn: 604800

# IDP configuration
idp:
  existingSecret: ""
  baseUrl: "http://idp-service:8080"
  clientId: ""
  clientSecret: ""

# OpenAI configuration
openai:
  existingSecret: ""
  apiKey: ""

# Database migration configuration
migration:
  enabled: true
  imageName: "traditional-saju-migration"
  version: "latest"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Node selector and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Monitoring
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    path: /metrics
