{{- if .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traditional-saju.fullname" . }}
  labels:
    {{- include "traditional-saju.app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "traditional-saju.app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/app/configmap.yaml") . | sha256sum }}
        checksum/db-secret: {{ include (print $.Template.BasePath "/shared/db-secret.yaml") . | sha256sum }}
        checksum/redis-secret: {{ include (print $.Template.BasePath "/shared/redis-secret.yaml") . | sha256sum }}
        {{- if not .Values.jwt.existingSecret }}
        checksum/jwt-secret: {{ include (print $.Template.BasePath "/shared/jwt-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if not .Values.idp.existingSecret }}
        checksum/idp-secret: {{ include (print $.Template.BasePath "/shared/idp-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if not .Values.openai.existingSecret }}
        checksum/openai-secret: {{ include (print $.Template.BasePath "/shared/openai-secret.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "traditional-saju.app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "traditional-saju.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.app.imageName }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "traditional-saju.app.configMapName" . }}
            - secretRef:
                name: {{ include "traditional-saju.databaseSecretName" . }}
            - secretRef:
                name: {{ include "traditional-saju.redisSecretName" . }}
            - secretRef:
                name: {{ include "traditional-saju.jwtSecretName" . }}
            - secretRef:
                name: {{ include "traditional-saju.idpSecretName" . }}
            - secretRef:
                name: {{ include "traditional-saju.openaiSecretName" . }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
