apiVersion: v1
kind: Service
metadata:
  name: {{ include "saju-core.fullname" . }}
  labels:
    {{- include "saju-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "saju-core.selectorLabels" . | nindent 4 }}
