{{- if not .Values.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traditional-saju.redisSecretName" . }}
  labels:
    {{- include "traditional-saju.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_MODE: {{ .Values.redis.mode | default "standalone" | b64enc }}
  {{- if eq (.Values.redis.mode | default "standalone") "standalone" }}
  REDIS_HOST: {{ .Values.redis.host | b64enc }}
  REDIS_PORT: {{ .Values.redis.port | toString | b64enc }}
  {{- else if eq .Values.redis.mode "sentinel" }}
  REDIS_SENTINELS: {{ .Values.redis.sentinels | b64enc }}
  REDIS_SENTINEL_NAME: {{ .Values.redis.sentinelName | b64enc }}
  {{- if .Values.redis.sentinelPassword }}
  REDIS_SENTINEL_PASSWORD: {{ .Values.redis.sentinelPassword | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
  {{- end }}
  REDIS_DB: {{ .Values.redis.db | default 0 | toString | b64enc }}
{{- end }}
